grpc:
  server:
    port: 9090
spring:
  datasource:
    url: jdbc:h2:mem:poc
    username: poc
    password: grpc
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
